"""Update models with correct table names and relationships

Revision ID: 1c16e34cc6f7
Revises: 8a031157c788
Create Date: 2024-09-01 07:56:56.123727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c16e34cc6f7'
down_revision: Union[str, None] = '8a031157c788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
