"""Update models with correct table names and relationships

Revision ID: 7b4ad37c3195
Revises: 1c16e34cc6f7
Create Date: 2024-09-01 08:24:08.780493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4ad37c3195'
down_revision: Union[str, None] = '1c16e34cc6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
