"""Update models with correct table names and relationships

Revision ID: 9e85a0a1bf00
Revises: f77da3f67ab8
Create Date: 2024-09-01 09:16:31.888517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e85a0a1bf00'
down_revision: Union[str, None] = 'f77da3f67ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
