"""Update models with correct table names and relationships

Revision ID: b075f0a703be
Revises: 9e85a0a1bf00
Create Date: 2024-09-01 09:18:24.363627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b075f0a703be'
down_revision: Union[str, None] = '9e85a0a1bf00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
