"""Update models with correct table names and relationships

Revision ID: f77da3f67ab8
Revises: bfa4c20e8de7
Create Date: 2024-09-01 09:09:03.426323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77da3f67ab8'
down_revision: Union[str, None] = 'bfa4c20e8de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
